[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
ffi = true
optimizer = true
optimizer_runs = 10_000_000
solc_version = "0.8.30"
via_ir = true

[fmt]
bracket_spacing = true
line_length = 100
